# -*- coding: utf-8 -*-
"""TP-STAP_Quairel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMd8s5lPP3lkRXlHAhlYJYa_TUA0gtmD
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat
import scipy.linalg as linalg
import scipy.stats as st
from scipy.stats import ttest_ind
from scipy.stats import chi2_contingency

"""# Introduction

Les tests statistiques constituent des outils essentiels pour l’analyse de données dans de nombreux contextes du quotidien. Qu’il s’agisse, comme dans ce travail pratique, de l’étude des tailles d’individus, ou de problématiques plus sensibles telles que l’évaluation du risque d’erreur dans un diagnostic médical, les tests statistiques, associés aux intervalles de confiance, permettent d’éclairer la prise de décision des spécialistes s'ils sont bien mit en place.

Dans ce TP, nous commencerons par explorer une expérience illustrant le théorème de la limite centrale. Nous poursuivrons avec une étude des intervalles de confiance, avant d’analyser une distribution de tailles humaines afin d’appliquer et de mieux comprendre différents tests statistiques.

Ce compte rendu est réalisé par Raphael Törnqvist et Arthur Quairel, élèves du groupe 1 .

# Exercice à partir de données synthétiques

Dans cet exercice, nous allons nous même engendrer les données afin d'expérimenter le theorème de la limite centrale (ou TCL).

Le théorème de la limite centrale, de façon informelle, donne une estimation précise de l'erreur que l'on commet en approchant l'espérance mathématique par la moyenne arithmétique (historiquement nommé théorème des erreurs par Gauss).

Soit $X_n$ une suite de v.a. de même loi d'espérance $\mu$ et d'écart type $\sigma$. Alors la v.a.
$$ Z_n = \frac{(X_1 + \cdots + X_n) -n\mu}{\sigma\sqrt{n}} \longrightarrow \mathcal{N}(0,1)$$

dit autrement:

$$ \frac{(X_1 + \cdots + X_n)}{n} \longrightarrow \mathcal{N}(\mu,\frac{\sigma}{\sqrt{n}})$$

et aussi:
$$ (X_1 + \cdots + X_n) \longrightarrow \mathcal{N}(n\mu,\sigma*\sqrt{n})$$

Prenons $n$ échantillons au hasard dans une population telle que la caractéristique observée est normée centrée.
"""

n=10
samples = np.random.randn(n)
#samples = np.random.randn(n)*ecart*np.sqrt(n)+ n*moyenne
samples.mean()

"""La moyenne n'est pas proche de 0 ! Ainsi en observant que ces $n$ valeurs, notre estimation de la moyenne n'est pas très bonne. Mais c'est peut être qu'on a pas eu de chance.  Alors recommençons ! Dans ce cas l'estimateur de la moyenne d'après un échantillonage de $n$ valeur devient lui même une variable aléatoire."""

M1 = 100 # Pour M = 100
L1=[]
for i in range(M1):
  L1.append(np.random.randn(n).mean()) #Création de la liste contenant les M1 valeurs moyennes des echantillons de 10 variables

plt.figure(figsize=(15, 5))

plt.subplot(1,3,1) # Tracé de l'histogramme des estimations pour M = 100
plt.hist(L1, bins=30, density=True, color='lightgreen',edgecolor='black')
plt.title(f'M = {M1} estimations')



M2 = 1000 # Pour M = 1000
L2=[]
for i in range(M2):
  L2.append(np.random.randn(n).mean()) #Création d'une liste avec plus de valeurs moyennes car M2>M1

plt.subplot(1,3,2) # Tracé de l'histogramme des estimations pour M = 1000
plt.hist(L2, bins=50, density=True, color='lightgreen',edgecolor='black')
plt.title(f'M = {M2} estimations')


M3 = 10000 # Pour M = 10000
L3=[]
for i in range(M3):
  L3.append(np.random.randn(n).mean())

plt.subplot(1,3,3) # Tracé de l'histogramme des estimations pour M = 10000
plt.hist(L3, bins=100, density=True, color='lightgreen',edgecolor='black')
plt.title(f'M = {M3} estimations')


plt.tight_layout()
plt.show()

"""On remarque que plus on fait d'estimations plus la répartitions de nos moyennes  tend vers une gaussienne centrée réduite. Ce résultat est d'autant plus vrai que la valeur de M est importante. Pour M = 100, on remarque une tendance de gausienne, alors que pour M = 10000 il est clair que la l'histogramme est une gausienne. Cette simulation permet de confirmer le théorème central limite.

L'estimation est une somme de $n=10$ variables aléatoires , chacune normale et normalisée sur $n$. Une somme de gaussienne avec même variance, reste une gaussienne.

On voit que sur 100 échantillonnages différents (chacun prenant 10 valeurs),  l'estimation de la moyenne est très incertaine. Si on augmente $n$ est-ce  que serait mieux ?
"""

# Tracer l'histogramme des estimations pour chaque n.

M=100 # cette fois  M est fixé à 100
n1=10 # et n varie : 10, 100, 1000, 10000
n2=100
n3=1000
n4=10000


plt.figure(figsize=(20, 5))


L1=[]
for i in range(M):
  L1.append(np.random.randn(n1).mean()) #Création de la liste comprennant les M valeurs moyennes des échantillons de tailles n1

plt.subplot(1,4,1) # Tracé de l'histogramme des estimations pour n = 10
plt.hist(L1, bins=30, density=True, color='salmon',edgecolor='black')
plt.title(f'n = {n1} variables aléatoires')


L2=[]
for i in range(M):
  L2.append(np.random.randn(n2).mean()) #Création de la liste comprenant les M valeurs moyennes des échantillons de tailles n2

plt.subplot(1,4,2) # Tracé de l'histogramme des estimations pour n = 100
plt.hist(L2, bins=30, density=True, color='salmon',edgecolor='black')
plt.title(f'n = {n2} variables aléatoires')



L3=[]
for i in range(M):
  L3.append(np.random.randn(n3).mean())

plt.subplot(1,4,3) # Tracé de l'histogramme des estimations pour n = 1000
plt.hist(L3, bins=30, density=True, color='salmon',edgecolor='black')
plt.title(f'n = {n3} variables aléatoires')


L4=[]
for i in range(M):
  L4.append(np.random.randn(n4).mean())

plt.subplot(1,4,4) # Tracé de l'histogramme des estimations pour n = 10000
plt.hist(L4, bins=30, density=True, color='salmon',edgecolor='black')
plt.title(f'n = {n4} variables aléatoires')

"""On voit que la variance de l'estimateur diminue avec $n$, mais on voit aussi qu'augmenter la taille de l'échantillon ne modifie pas drastiquement l'histogramme.



Toute la question est alors: à partir de mon échantillon, mon estimation de la moyenne est-elle fiable ou pas. On peut alors choisir non pas d'estimer cette moyenne mais de déterminer un intervalle de confiance.  

## Intervalle de confiance

De manière générale, le paramètre à estimer à partir d'un échantillon est $\theta$:
- Soit $\alpha \in ]0, 1[$ le niveau de risque.
- S’il existe des v.a.r $\theta_{min}(X1, . . . , Xn)$ et $\theta_{max}(X1, . . . , Xn)$
 telles que
 $$ P(\theta \in [\theta_{min}, \theta_{max}]) = 1 − \alpha$$

On dit alors que $[\theta_{min}, \theta_{max}]$ est un intervalle de
confiance pour $\theta$, avec coefficient de sécurité $1 − \alpha$. On le note $IC_{1−\alpha}(\theta)$. Dit autrement, si on effectue plein d'échantillonnage, la probabilité d'observer la valeur $\theta$ dans l'IC est de $1-\alpha$.


## Pour la moyenne
Si on souhaite estimer la moyenne empirique à partir de $n$ échantillons, partons
du TCL,
$$ \bar{X_n} = \frac{(X_1 + \cdots + X_n)}{n} $$

$$ Z_n = \sqrt{n}\big(\frac{ \bar{X_n}-  \mu}{\sigma} \big) \longrightarrow \mathcal{N}(0,1)$$

On cherche $\theta_{min}$ et $\theta_{max}$ tq
$$ P( \theta_{min}  < Z_n < \theta_{max} ) = 1 -\alpha$$

- $Z_n$ tend vers une loi normale, centrée réduite donc
$\theta_{min} = - \theta_{max} = -z_{1-\alpha/2}$.
- La probabilité $\alpha$ se répartit en 2 parties égales à $\alpha/2$


"""

x = np.linspace(-5,5,1000)
y = st.norm.pdf(x) # par defaut N(0,1)
plt.grid()
plt.plot(x,y)
plt.title('La loi normale centrée réduite')

for alpha in [0.01, 0.05, 0.1]: #Mise en place de la liste d'alpha que nous allons tester
    xcritic = abs(st.norm.ppf(alpha/2)) #Calcul de la valeur critique pour l'intervalle de confiance
    print(f"Pour α = {alpha}: Valeur critique (absolue) = {xcritic:.4f}")

"""Ici nous avons montré qu'en fonction des valeurs de α que l'on choisit, la valeur critiqeu de début et de fin de l'intervalle de confiance varie assez conséquement, on pouvait s'y attendre sachant qu'on passe d'un intervalle de confiance de 99 % à un intervalle de 90%.  """

alpha = 0.05 # Intervalle de confiance à 95 %
xcritic=st.norm.ppf(alpha/2)
#plt.plot(x,y)
sel = x < xcritic
#plt.fill_between(x[sel],y[sel], 0, color='red', edgecolor='black',alpha=1)
sel = x >  - xcritic
#_ = plt.fill_between(x[sel],y[sel], 0, color='red', edgecolor='black',alpha=1)
#plt.grid()
#plt.title('Intervalle de confiance à 95% ')




xcritic_left = st.norm.ppf(alpha/2)   # Borne inférieure
xcritic_right = -xcritic_left          # Borne supérieure


plt.figure(figsize=(10, 6))
plt.plot(x, y, 'b-', linewidth=2, label='Distribution normale standard')

#On remplit et les zones de rejet et l'intervalle de confance
plt.fill_between(x[x < xcritic_left], y[x < xcritic_left], 0,
                color='red', alpha=0.5, label=f'Zone de rejet (α/2 = {alpha/2:.3f})')
plt.fill_between(x[x > xcritic_right], y[x > xcritic_right], 0,
                color='red', alpha=0.5)

plt.fill_between(x[(x >= xcritic_left) & (x <= xcritic_right)],
                 y[(x >= xcritic_left) & (x <= xcritic_right)], 0,
                 color='green', alpha=0.3,
                 label=f'Intervalle de confiance (1-α = {(1-alpha):.0%})')

# Lignes critiques pointillées
plt.axvline(x=xcritic_left, color='black', linestyle='--',
            label=f'Borne critique = {xcritic_left:.2f}')
plt.axvline(x=xcritic_right, color='black', linestyle='--')

plt.title(f'Intervalle de confiance à {(1-alpha):.0%}\n'
          f'(α = {alpha}, Valeurs critiques = [{xcritic_left:.2f}, {xcritic_right:.2f}])',
          pad=20)
plt.xlabel('Valeurs standardisées')
plt.ylabel('Densité de probabilité')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

"""Nous avons donc tracé l'intervalle de confiance pour un alpha de 0.05, en prenant comme distribution le fait qu'avec le TCL :
$$ Z_n \longrightarrow \mathcal{N}(0,1)$$

Une fois l'IC trouvé sur $Z_n$, reste à revenir à $\bar{X_n}$ en isolant $\mu$

$$ IC_{1-\alpha}(\mu) = \big[ \bar{X_n} - z_{1-\alpha/2}\frac{\sigma}{\sqrt n} ; \bar{X_n} + z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}} \big]
$$
Pour $\alpha = 0.05$,  la valeur critique $z_{1+\alpha/2} \approx 1.96$.

L'intervalle de confiance dépend alors que de $\alpha, n, \sigma$:
- plus $n$ augmente, plus l'intervalle se réduit autour de la valeur estimée.
- plus $\sigma$ est grand plus il est difficile d'avoir une estimation certaine car le processus sous-jacent est lui-même incertain.
"""

# Paramètres de la simulation
n = 30          # Taille de l'échantillon
alpha = 0.05    # Niveau de signification
T = 10000       # Nombre de répétitions
xcritic = abs(st.norm.ppf(alpha / 2))  # Valeur critique théorique (pour un test bilatéral)
compteur = 0    # Compteur d'intervals "corrects" (qui contiennent la vraie moyenne)

for _ in range(T):
    # Génération d'un échantillon et calcul de sa moyenne
    echantillon = np.random.randn(n)
    moyenne_echantillon = echantillon.mean()
    # Vérification si la moyenne est dans l'intervalle de confiance théorique
    if -xcritic/np.sqrt(n)< moyenne_echantillon < xcritic/np.sqrt(n):
        compteur += 1

# Calcul des résultats
taux_empirique = (compteur / T) * 100      # % observé
taux_theorique = (1 - alpha) * 100         # % théorique attendu

# Affichage clair des résultats
print("=== Résultats de la simulation ===")
print(f"• Taille d'échantillon (n) : {n}")
print(f"• Nombre de répétitions (T) : {T}")
print(f"• Estimations de la moyenne à partir d'un échantillon de n=30 valeurs : {moyenne_echantillon}")
print(f"• Niveau de confiance théorique (1 - α) : {taux_theorique:.2f}%")
print("-----------------------------------")
print(f"• Taux empirique de réussite : {taux_empirique:.2f}%")
print(f"• Écart théorique/empirique : {abs(taux_theorique - taux_empirique):.2f}%")
print("===================================")

"""Le résultat de ce calcul est important car il permet de bien interpréter le sens de l'intervalle de confiance.

## Mais la variance n'est pas connue !
- Comment procéder ? Quelle loi utiliser ?
- A partir d'un échantillon de $n=10$, calculer le nouvel intervalle de confiance.  

Lorsqu'on ne connaît pas la variance d'une population, on ne peut pas utiliser la loi normale directement, car cette loi suppose que la variance est connue. C'est le cas souvent lorsqu'on s'intéresse à de petits échantillons. Pour ce faire, on utilise la loi de Student qui ne fais intervenir que l'écart type empirique de notre échantillon s.
L'intervalle de confiance peut s'écrire ;

$$ IC_{1-\alpha} = \big[ \bar{X_n} - \left| F^{-1}_{T_{n-1}}(\frac{\alpha}{2}) \right|\frac{s}{\sqrt n} ; \bar{X_n} +  \left|F^{-1}_{T_{n-1}}(\frac{\alpha}{2}) \right|\frac{s}{\sqrt{n}} \big]
$$

Avec $F^{-1}_{T_{n-1}}(\frac{\alpha}{2}) $ la fonction inverse de la répartition de la distribution t de Student.
"""

# Paramètres de la simulation
n = 5       # Taille de l'échantillon
alpha = 0.05    # Niveau de signification
T = 10000       # Nombre de répétitions
xcritic = abs(st.t.ppf(alpha / 2, n-1))  # Valeur critique théorique avec la loi de student
compteur = 0    # Compteur d'intervals "corrects" (qui contiennent la vraie moyenne)

for _ in range(T):
    # Génération d'un échantillon et calcul de sa moyenne
    echantillon = np.random.randn(n)
    moyenne_echantillon = echantillon.mean()
    ecart = np.std(echantillon, ddof=1)

    # Vérification si la moyenne est dans l'intervalle de confiance théorique
    if -xcritic/np.sqrt(n)*ecart < moyenne_echantillon < xcritic/np.sqrt(n)*ecart:
        compteur += 1

# Calcul des résultats
taux_empirique = (compteur / T) * 100      # % observé
taux_theorique = (1 - alpha) * 100         # % théorique attendu

# Affichage clair des résultats
print("=== Résultats de la simulation ===")
print(f"• Taille d'échantillon (n) : {n}")
print(f"• Nombre de répétitions (T) : {T}")
print(f"• Estimations de la moyenne à partir d'un échantillon de n=30 valeurs : {moyenne_echantillon}")
print(f"• Niveau de confiance théorique (1 - α) : {taux_theorique:.2f}%")
print("-----------------------------------")
print(f"• Taux empirique de réussite : {taux_empirique:.2f}%")
print(f"• Écart théorique/empirique : {abs(taux_theorique - taux_empirique):.2f}%")
print("===================================")

"""

# Analyse statistique de données
Cet exercice nécessite les fichiers de données suivant (à télécharger sur moodle): `dataA.txt`.  


Dans son [article fondateur sur la régression](http://www.stat.ucla.edu/~nchristo/statistics100C/history_regression.pdf), Francis Galton a étudié les tailles moyennes
de 205 couples ainsi que celles de leurs enfants. Nous nous intéressons ici aux tailles des parents seulement. Ces tailles, exprimées en pouces, sont fournies dans le fichier  `dataA.txt` (la première colonne correspond aux pères, la seconde aux mères).

"""

data = np.loadtxt("dataA.txt") # modifier le chemin si nécessaire

"""Explorons ces données.
- Afficher les histogrammes des tailles des pères et des mères.
- Afficher également les histogrammes cumulés.
- Une autre manière de visualiser les données est de regarder les "boîtes à moustaches" ou `boxplot`. Cette fonction existe dans matplotlib. Regarder la documentation et utiliser là. Comprendre les quantités en présence.  
- Trouver les fonctions permettant de calculer les estimations de l’espérance mathématique, de la variance, et de l’écart-type de la distribution des tailles.
- Trouver aussi les estimateurs biaisés de la variance et de l’écart-type.
- Trouver également les fonctions fournissant les coefficients d’asymétrie et d’aplatissement (idem, il en existe des versions biaisées et non biaisées). Vérifier la cohérence de leurs valeurs avec les histogrammes.


"""

plt.figure(figsize=(15, 10))

tailles_peres= data[:, 0]
tailles_meres= data[:, 1]


plt.subplot(2, 3, 1)
plt.hist(tailles_peres, bins=30, color='skyblue', edgecolor='black')
plt.title('Distribution des tailles des pères')
plt.xlabel('Taille (cm)')
plt.ylabel('Fréquence')

plt.subplot(2, 3, 2)
plt.hist(tailles_meres, bins=30, color='salmon', edgecolor='black')
plt.title('Distribution des tailles des mères')
plt.xlabel('Taille (cm)')

# 2. Histogrammes cumulés
plt.subplot(2, 3, 4)
plt.hist(tailles_peres, bins=30, color='skyblue', edgecolor='black', cumulative=True, density=True)
plt.title('Distribution cumulée (pères)')
plt.xlabel('Taille (cm)')
plt.ylabel('Fréquence cumulée')

plt.subplot(2, 3, 5)
plt.hist(tailles_meres, bins=30, color='salmon', edgecolor='black', cumulative=True, density=True)
plt.title('Distribution cumulée (mères)')

plt.figure(3) #tracé des moustaches
plt.boxplot([data[:, 0], data[:, 1]], labels=['Pères', 'Mères'],vert=False, patch_artist=True, boxprops=dict(facecolor='lightblue') )
plt.title('Boîtes à moustaches')
plt.xlabel('Taille (cm)')

plt.tight_layout()
plt.show()


def print_stats(name, data):
    print(f"\n--- Statistiques pour {name} ---")
    print(f"Moyenne (estimateur non biaisé): {np.mean(data):.2f} cm")
    print(f"Variance non biaisée (n-1): {np.var(data, ddof=1):.2f}")
    print(f"Variance biaisée (n): {np.var(data, ddof=0):.2f}")
    print(f"Écart-type non biaisé: {np.std(data, ddof=1):.2f} cm")
    print(f"Écart-type biaisé: {np.std(data, ddof=0):.2f} cm")
    print(f"Asymétrie biaisé (skewness): {st.skew(data,bias=True):.2f}")
    print(f"Asymétrie non biaisé (skewness): {st.skew(data,bias=False):.2f}")
    print(f"Aplatissement biaisé (kurtosis): {st.kurtosis(data,bias=True):.2f}")
    print(f"Aplatissement non biaisé (kurtosis): {st.kurtosis(data,bias=False):.2f}")
    print("===================================")

print_stats("les pères", tailles_peres)
print_stats("les mères", tailles_meres)

plt.figure(2) #Comparaison des 2 histogrammes
plt.hist(data.T[1], color = 'salmon', bins = 'rice', density=True, label= "mère",edgecolor='black')
plt.hist(data.T[0], color = 'skyblue', bins = 'rice', density=True, label = "père",edgecolor='black')
plt.legend()
plt.title("Comparaison des 2 histogrammes")

"""On remarque qu'il n'y a pas de différence entre les coefficients d'aplatissement et d'asymétrie biaisés et non biaisés.

Pour les mères, les deux coefficients d'asymétrie sont très proches de zéro (+0,012). Cela indique que les distributions sont quasiment symétriques. Une asymétrie aussi faible signifie qu’il n’y a pas de queue dominante, ni à gauche ni à droite. Les coefficients d'aplatissement sont négatifs (–0,18). Cela signifie que les distributions sont moins pointues qu’une loi normale, avec des queues plus fines (moins de valeurs extrêmes).

# Test de conformité

Le  test nommé *chi-square goodness-of-fit test* détermine si un échantillon de données peut être considéré comme issu d'une distribution de probabilité dont les paramètres pourraient être estimés à partir des observations.  Le test regroupe les données selon des groupes et calcul les comptes observés et attendus (selon la distribution hypothèse). Ici on part de l'histogramme, les groupes peuvent se déduire donc de l'histogramme surtout si on a défini nous-même les intervalles. Puis les effectifs sont comparés grâce à la loi du $\chi^2$:

$$\chi^2=\sum_{i=1}^{N} \frac{(O_i−E_i)^2}{E_i} ,$$

avec $O_i$ les comptes observés et $E_i$ les comptes attendus. La statistique de test suit alors une loi du $\chi^2$ quand les comptes sont suffisants. Notons que la convergence de la distribution du $\chi^2$ est asymptotique mais, en pratique, l’approximation est correcte si $E_i \geq 5\ \ \forall i$.


Pour tester la conformité des données (les deux colonnes) vis-à-vis d'une distribution gaussienne:

- On peut appliquer à l'histogramme un test du $\chi^2$. Quelles sont les grandeurs que l'on veut comparer ? Comment les calculer ? Représenter ces grandeurs graphiquement. On souhaite comparer les données empiriques des tailles des personnes avec une gausienne théoriques. On détermine la forme de la gausienne théorique à l'aide de la moyenne et de l'écart-type.
- Tester le caractère gaussien des deux distributions à l’aide du test de $\chi^2$ de conformité à une distribution. Il faut faire attention à comment on choisit les intervalles !

Théoriquement, on peut déterminer les quantiles thèoriques d'une loi normal. La $i^{ème}$ valeur correspond en moyenne au quantile $p_i = \frac{i-0.5}{n}$ de la loi. On peut alors déterminer le quantile normale par la fonction quantile $z_i = \phi^{-1}(p_i)$

- Tracer et interpréter les diagrammes quantile-quantile des distributions.
- Calculer la droite de Henri.
Théotiquement la droite de Henri pour une loi normal à une équation $ y = \mu + z \times \sigma$
"""

#Pour les tailles des pères
tailles_peres= data[:, 0]
n = len(tailles_peres)


moyenne = np.mean(tailles_peres)
ecart = np.std(tailles_peres)
V = np.std(tailles_peres)
M = 15 # pour contrôler le nombre de bins dans la distribution
X = 0

plt.figure(1) # On représente l'histogramme des
h2, bins, p  = plt.hist(tailles_peres,bins = M , density=False, color='skyblue', edgecolor='black') # On représente l'histogramme des tailles des pères


E = st.norm.cdf(bins[1:], loc=moyenne, scale=ecart) - st.norm.cdf(bins[:-1], loc=moyenne, scale=ecart) # On détermine les E(i) attendus à partir de la moyenne et de l'ecart type. On soustrait les fonctions de répartition en décalé pour avoir accès à l'aire sous la courbe.

plt.figure(2)
plt.plot(E*n, color = 'r', label = 'attendus')
plt.hist(tailles_peres-63,bins = M , density=False, color='skyblue', edgecolor='black')
plt.plot(h2,color = 'b', label = 'observés')
plt.legend()
plt.title("Comparaison des courbes de distributions observées et attendus")

X = (h2-E*n)**2/(E*n)


print(f"La valeur de Z pour les pères est :",  np.sum(X) )
print('======================================')


Taille = np.sort(tailles_peres)  # On trie les tailles des pères
prob_theoriques = (np.arange(1, n+1) - 0.5) / n # Calcul des probabilités théoriques

z_theoriques = st.norm.ppf(prob_theoriques) # Valeurs normales théoriques (quantiles)


# Tracé de la droite de Henry
plt.figure()
plt.plot(z_theoriques, Taille, 'o', label = "Quantile- Quantile")
plt.plot(z_theoriques, moyenne + ecart*z_theoriques, label = "droite d'Henri")
plt.legend()
plt.title("Droite de Henry")
plt.xlabel("Quantiles théoriques (normale)")
plt.ylabel("Quantiles empiriques (Données triées)")
plt.grid(True)
plt.show()

#Pour les tailles des mères
tailles_meres= data[:, 1]
n = len(tailles_meres)


moyenne = np.mean(tailles_meres)
ecart = np.std(tailles_meres)
V = np.std(tailles_meres)
M = 15 # pour contrôler le nombre de bins dans la distribution
X = 0

plt.figure(1) # On représente l'histogramme des tailles des femmes
h1, bins, p  = plt.hist(tailles_meres,bins = M , density=False, color='salmon',edgecolor='black') # On représente l'histogramme des tailles des pères


E = st.norm.cdf(bins[1:], loc=moyenne, scale=ecart) - st.norm.cdf(bins[:-1], loc=moyenne, scale=ecart) # On détermine les E(i) attendus à partir de la moyenne et de l'ecart type. On soustrait les fonctions de répartition en décalé pour avoir accès à l'aire sous la courbe.

plt.figure(2)
plt.plot(E*n, color = 'b', label = 'attendus')
plt.plot(h1,color = 'r', label = 'observés')
plt.hist(tailles_meres-57.5,bins = M , density=False, color='salmon',edgecolor='black')
plt.legend()
plt.title("Comparaison des courbes de distributions observées et attendus")

X = (h1-E*n)**2/(E*n)


print(f"La valeur de Z pour les mères  est :",  np.sum(X) )
print('======================================')



Taille = np.sort(tailles_meres)  # On trie les tailles des pères
prob_theoriques = (np.arange(1, n+1) - 0.5) / n # Calcul des probabilités théoriques

z_theoriques = st.norm.ppf(prob_theoriques) # Valeurs normales théoriques (quantiles)


# Tracé de la droite de Henry
plt.figure()
plt.plot(z_theoriques, Taille, 'o',color= 'salmon', label = "Quantile- Quantile")
plt.plot(z_theoriques, moyenne + ecart*z_theoriques, label = "droite d'Henri")
plt.legend()
plt.title("Droite de Henry")
plt.xlabel("Quantiles théoriques (normale)")
plt.ylabel("Quantiles empiriques (Données triées)")
plt.grid(True)
plt.show()

"""Pour les pères, on obtient des résultats empiriques qui sont bien alignés sur la droite de Henry, ce qui signifie que les données suivent bien la distribution de la loi normale.
Pour les mères, les résultats empiriques sont moins bien alignés sur la droite de Henry, ce qui signifie que les données ne suivent pas parfaitement la distribution de la loi normale.
Par ailleurs, on observe que le Z pour les pères (14) est plus petit que le Z pour les mères (43), ce qui témoigne du fait que les valeurs pour les pères suivent davantage une loi normale. En effet, cela signifie que l'intervalle de confiance des valeurs est plus important.

Nous avons déterminé que l'un des deux (ou les deux ?) échantillons provenaient d'une distribution gaussienne. Commençons par calculer les intervalles de confiance des deux moyennes pour comparer ces deux estimateurs. Puis, en utilisant le test de student pour déterminer si les moyennes des distributions sont différentes, ou pas:
- Construire les intervalles de confiance des deux moyennes (avec degrés de confiance 0.95).
- Préalablement au test de student, déterminer si les variances des deux distributions sont égales.
- Effectuer le test de student ou welch avec : $$H_0: \mu_1 = \mu_2$$.
"""

#On détermine les intervalles de confiance pour les pères

moyennep = np.mean(tailles_peres)
ecartp = np.std(tailles_peres)
Vp = np.std(tailles_peres)
z = st.norm.ppf(1 - alpha/2)
IC1 = (moyennep - z * ecartp /np.sqrt(n), moyennep + z *ecartp /np.sqrt(n))

#On détermine les intervalles de confiance pour les mères
moyennem = np.mean(tailles_meres)
ecartm = np.std(tailles_meres)
Vm = np.std(tailles_meres)
z = st.norm.ppf(1 - alpha/2)
IC2 = (moyennem - z * ecartm /np.sqrt(n), moyennem + z *ecartm /np.sqrt(n))

print("IC 95% moyenne pères :", IC1)
print("IC 95% moyenne mères :", IC2)

import matplotlib.pyplot as plt
import numpy as np

# Moyennes et intervalles de confiance à 95 %
labels = ['Pères', 'Mères']
moyennes = [moyennep, moyennem]
basses = [IC1[0], IC2[0]]
hautes = [IC1[1], IC2[1]]
erreurs_inf = [moyennep - IC1[0], moyennem - IC2[0]]
erreurs_sup = [IC1[1] - moyennep, IC2[1] - moyennem]


x = [0.9, 1.1]

fig, ax = plt.subplots(figsize=(8, 6))

# Tracé avec barres d'erreur
ax.errorbar(
    x, moyennes, yerr=[erreurs_inf, erreurs_sup],
    fmt='o', capsize=8, color='navy', ecolor='skyblue',
    label="Intervalle de confiance à 95 %"
)

ax.set_title("Taille moyenne avec intervalle de confiance à 95 %", fontsize=14)
ax.set_ylabel("Taille moyenne (cm)", fontsize=12)
ax.set_ylim(min(basses) - 2, max(hautes) + 2)
ax.set_xlim(0.5, 1.5)
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.grid(True, linestyle='--', alpha=0.6)


ax.legend(loc='upper right')
for i, moyenne in enumerate(moyennes):
    ax.annotate(f"{moyenne:.2f} cm", (x[i], moyennes[i] + 0.5), ha='center', fontsize=10)


plt.tight_layout()
plt.show()

"""Nous souhaitons savoir si les variances des deux listes sont égales. On émet alors l'hypothèse $H_0 : \sigma_1^2 = \sigma_1^2$.

Nous construisons la variable aléatoire de Fisher-Snedecor.
Cette variable aléatoire (si $H_0$ est vrai) vérifie  :
$F = \frac{S1 \sigma_2^2}{S2 \sigma_1^2} ≈ F_{n_1-1, n_2-1}$

$H_0$ est vrai si : $f_{\alpha /2}(n_1-1,n_2-1) < f = (\frac{s_1}{s_2})^2 < f_{1- \alpha /2}(n_1-1,n_2-1)$
"""

n = len(tailles_peres)
f = ecartp**2/ecartm**2
f1 = st.t.ppf(alpha/2, 2*n -2)
f2 = st.t.ppf(1-alpha/2, 2*n -2)

print(f"Statistique f calculée : {f:.4f}")
print(f"Intervalle de confiance pour F au seuil de 5 % : [{f1:.4f} ; {f2:.4f}]")

if f1 < f < f2:
    print("→ La statistique F est dans l'intervalle de confiance : on accepte l'hypothèse H0.")
    print("→ Conclusion : les variances des deux échantillons peuvent être considérées comme égales au seuil de 5 %.")

"""On peut conclure que les variances des deux listes sont égales avec un risque de 5 %.

- Pour effectuer un Test de Welch, il faut calculer la statistique $$ T = \frac{\bar{Y_1} - \bar{Y_2}}{S \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}} ≈ 𝚪_{n_2 + n_1 -2}$$
Si l'hypothèse $H_0$ est vérifiée, alors $t < t_{\alpha /2}(n_1 +n_1 -2)$
"""

t = (moyennem -moyennep)/(ecartp*np.sqrt(2/n))
tf = st.t.ppf(alpha/2, 2*n -2)
print(f"Valeur de t : {t}")
print(f"Intervalle de confiance à 95 % : [{tf}, {-tf}]")

if tf < t < -tf:
    print("✅ La statistique t appartient à l'intervalle de confiance : on **accepte** l'hypothèse nulle H₀.")
else:
    print("❌ La statistique t est en dehors de l'intervalle de confiance : on rejette l'hypothèse nulle H₀.")

"""L'hypothèse $H_0$ n'est pas vérifiée ce qui implique que les deux moyennes sont différentes avec un risque de moins de 5%.

# Hypercholestérolémie primaire en monothérapie
Une étude randomisée en double aveugle contre placebo a été menée sur 827 patients traités à l’hypocholestérolémiant, et 892 patients auxquels a été administré un placebo. Pour chaque patient, on a mesuré la variation du taux de cholestérol LDL (Low Density Lipoprotein, ou mauvais cholestérol) entre le début et la fin du
traitement. Les résultats sont les suivants :

|   | traitement | placebo |
|---|------------|---------|
| effectifs F | 428   | 502  |
| effectifs H | 399  | 390  |
|   25-44 ans |  162    |  210 |
| 45-64 ans  | 403|423 |
| sup 65 ans  | 262 | 259 |
| $\sum$ des variations | – 528.4477 | -116.0837 |
| $\sum$ des écarts | 76.1925 | 35.8899 |


Pour la somme des variations et des écarts:
$$ \sum_k \delta_k \text{ en g/l et } \sum_k (\delta_k-\bar{\delta})^2$$


## Cohorte
Préalablement à l’étude statistique proprement dite, on souhaite s’assurer que les deux échantillons sont équilibrés entre eux, à la fois en âge et en sexe. Effectuer les tests adéquats. Pour tous les tests, que l’on effectuera avec un risque d’erreur de première espèce α = 5%, on explicitera les hypothèses non remises en question, l’hypothèse nulle et l’hypothèse alternative.


Puis calculer les estimations ponctuelles de l’espérance mathématique (e.m.), de la variance et de l’écart-type de la variation du taux de cholestérol LDL dans les deux groupes.

Afin de déterminer si les deux échantillons sont équilibrés entre eux en sexe, nous réalisons le test $H_0 : \mu_1 = \mu_2$ pour des grands echantillons. nous posons :  
$$ Z = \frac{\bar{Y_1} - \bar{Y_2}}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}} ≈ N(0,1)$$
Si l'hypothèse $H_0$ est vérifiée, alors $z < z_{\alpha /2}$.


Nous réalisons le test d'égalité des probabilités pour les hommes. Les lois pour les sexes suivent une loi binomial de paramètres $p_t = \frac{399}{827} = 48,25 \%$, $n_t = 827$ et $p_p = 43,72 \% $, $n_p = 892$. Les échantillons étant de grande taille on peut approximer les lois binomiales par des gausiennes.
"""

alpha = 0.05
traitement = [428, 399, 162, 403, 262, -528.4477, 76.1925]
placebo = [502, 390, 210, 423, 259, -116.0837, 35.8899]
alpha = 0.05
N_traitement = traitement[0] + traitement[1]
N_placebo = placebo[0] + placebo[1]



#On verifie l'homogénéité pour le sexe
table_sexe = np.array([[traitement[0], placebo[0]],
                       [traitement[1], placebo[1]]])

n_t = table_sexe[0][0]+table_sexe[1][0]
n_p = table_sexe[1][1]+table_sexe[0][1]
p_t = table_sexe[1][0]/(n_t)
p_p = table_sexe[1][1]/(n_p)


ecart_t = np.sqrt((1-p_t)*p_t*n_t)
ecart_p = np.sqrt((1-p_p)*p_p*n_p)

z = (p_t - p_p)/np.sqrt(ecart_t**2/n_t**2 + ecart_p**2/n_p**2)
z_test = st.norm.ppf(alpha/2)


# Affichage des résultats du test d'homogénéité pour le sexe
print("=== Test d'homogénéité des proportions hommes/femmes ===")
print(f"Taille échantillon traitement: {n_t} patients")
print(f"Taille échantillon placebo: {n_p} patients")
print(f"Proportion d'hommes dans le groupe traitement: {p_t*100:.2f}%")
print(f"Proportion d'hommes dans le groupe placebo: {p_p*100:.2f}%")
print("\n=== Résultats du test statistique ===")
print(f"Score z calculé: {z:.4f}")
print(f"Valeur critique pour alpha={alpha}: ±{abs(z_test):.4f}")
print("\n=== Conclusion ===")
if abs(z) < abs(z_test):
    print(f"Comme |{z:.4f}| < {abs(z_test):.4f}, nous ne rejetons pas H0.")
    print("Les deux échantillons sont homogènes concernant la répartition hommes/femmes avec un risque < à 5%")

"""Nous pouvons ainsi affirmer que les deux échantillons sont homogènes avec un risque moins de 5 %.


Pour vérifier l'homogénéité suivant l'âge, nous réalisons un test du chi carré.

$$D^2 =\sum{j=1}_a \sum_{i=1}^b \frac{(N_{ij}-\bar{N_{ij}})^2}{\bar{N_{ij}}}$$

Nous obtenons le tableau de continguence suivant :

|   | 25-44 ans | 45-64 ans |sup 65 ans|Total |
|----------|------------|---------| --------| |
| Traitement |  162 | 403  | 262  | 827|
| Placebo | 210 | 423 | 259  |892 |
|   Total |  372  |  826 | 521 | 1719
"""

#On verifie l'homogénéité pour l'âge
table_age = np.array([[traitement[2], placebo[2]],
                      [traitement[3], placebo[3]],
                      [traitement[4], placebo[4]]])
n = table_age[0][0]+table_age[0][1]+ table_age[1][0]+ table_age[1][1] +table_age[2][0] + table_age[2][1]

n11 = table_age[0][0]+table_age[0][1]
n12 = table_age[1][0]+table_age[1][1]
n13 = table_age[2][0]+table_age[2][1]

n21 = table_age[0][0]+table_age[1][0]+ table_age[2][0]
n22 = table_age[0][1]+table_age[1][1]+ table_age[2][1]

N12 = n11 * n22/n
N11 = n11 * n21/n
N21 = n12 * n21/n
N22 = n12 * n22/n
N31 = n13 * n21/n
N32 = n13 * n22/n
d2 = (table_age[0][0]-N11)**2/N11 + (table_age[0][1]-N12)**2/N12 + (table_age[2][0]-N31)**2/N31 + (table_age[1][0]-N21)**2/N21 + (table_age[1][1]-N22)**2/N22 + (table_age[2][1]-N32)**2/N32

C = st.chi2.ppf(1-alpha,2)

print("\n=== Test du Chi-deux sur la répartition par âge ===")
print(f"\nStatistique du test : D² = {d2:.3f}")
print(f"Seuil critique (α={alpha}) : {C:.3f}")

if d2 < C:
    print("\nConclusion : Les distributions d'âge sont homogènes (p > 0.05)")
    print(f"→ On accepte H0 (D² = {d2:.3f} < {C:.3f})")

"""L'homogénéité selon l'âge est bien vérifiée grâce au test du Chi-Deux"""

# Détermination des moyennes, écart-types et variances

moyenne_traitement = traitement[5]/N_traitement
ecart_traitement = traitement[6]/(N_traitement-1)
V_traitement = np.sqrt(ecart_traitement)
moyenne_placebo = placebo[5]/N_placebo
ecart_placebo = placebo[6]/(N_placebo-1)
V_placebo = np.sqrt(ecart_placebo)

print("===================================")
print(f"Moyenne traitement: {moyenne_traitement} g/L")
print(f"Ecart traitement: {ecart_traitement} ")
print(f"Variance traitemnt: {V_traitement} ")
print(f"Moyenne placebo: {moyenne_placebo} g/L")
print(f"Ecart placebo: {ecart_placebo} ")
print(f"Variance placebo: {V_placebo} ")
print("===================================")

"""## Efficacité

 Déterminer, en conduisant le(s) test(s) adéquat(s), si  l’hypocholestérolémiant est plus efficace que le placebo  pour ce type de patients. Donner des estimations ponctuelle et par intervalle (au  seuil de confiance 5%) de l’écart entre la diminution  obtenue avec le traitement et celle obtenue avec le  placebo.

Afin de déterminer, le moyen le plus efficace, on réalise un test de comparaison. Les effectifs sont très grands, Nous n'avons pas besoin de faire le test d'égalité des variance. Nous éméttons l'hypothèse $H_0 = \nu_t = \nu_p$

$$ Z = \frac{\bar{Y_t} - \bar{Y_p}}{\sqrt{\frac{s_t^2}{n_t} + \frac{s_p^2}{n_p}}} ≈ N(0,1)$$

Si l'hypothèse $H_0$ est vérifiée, alors $z < z_{\alpha /2}$.

On détermine le $\chi^2$, on réalise le teste de Student ou de Welsh et on compare au $\alpha$. Dans notre cas de figure, il y a une seule données par groupe (n=1). La fonction chi2_contingency() permet de réaliser tous nos calculs précédent directement.



Ainsi, on a deux banques de données qui sont équilibrées selon l'âge et le sexe. La répartition selon le sexe et l'âge est la même dans les deux groupes.
Autrement dit, sexe et groupe, et âge et groupe, sont indépendants. L'hypothèse nulle est vérifiée.
"""

z = (moyenne_traitement - moyenne_placebo)/np.sqrt(ecart_traitement/N_traitement +ecart_placebo/N_placebo)

z_test= st.norm.ppf(alpha/2)

print("=== Résultats du test Z ===")
print(f"Statistique Z = {z:.4f}")
print(f"Seuil critique (α=5%) = ±{abs(z_test):.4f}")
print("\n=== Conclusion ===")
print(f"Résultat du test : z = {z:.4f} < z_critique = {z_test:.4f}")
print("→ On rejette H0 : le traitement est significativement plus efficace que le placebo avec un risque de 5%")

"""Nous en déduisons que le traitement est plus efficace que le placebo avec un risque de 5% de se tromper.

Pour déterminer des estimations ponctuelle et par intervalle (au  seuil de confiance 5%) de l’écart entre la diminution  obtenue avec le traitement et celle obtenue avec le  placebo, nous posons :

$$ \bar{Y} = \frac{\bar{Y_t} - \bar{Y_p} - (\mu_t-\mu_p)}{\sqrt{\frac{s_t^2}{n_t} + \frac{s_p^2}{n_p}}} ≈ N(0,1)$$
"""

# Calcul de l'intervalle de confiance
diff = moyenne_traitement - moyenne_placebo
std_error = np.sqrt((ecart_traitement**2)/N_traitement + (ecart_placebo**2)/N_placebo)
z_critique = st.norm.ppf(1 - alpha/2)  # Valeur critique bilatérale

IC_inf = diff - z_critique * std_error
IC_sup = diff + z_critique * std_error

print("\n=== Estimation de l'effet traitement ===")
print(f"Différence moyenne (Traitement - Placebo) : {diff:.2f}")
print(f"Erreur standard de la différence : {std_error:.4f}")
print("\nIntervalle de confiance à 95% :")
print(f"[{IC_inf:.2f} ; {IC_sup:.2f}]")
print("\nInterprétation :")
print("Avec 95% de confiance, la vraie différence d'efficacité entre le traitement")
print(f"et le placebo se situe entre {IC_inf:.2f} et {IC_sup:.2f} unités.")



"""En regardant les intervalles de confiances, on peut dire que la méthode de traitement est plus efficace que celle du placebo."""